# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1121, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_titel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_titel.setFont(font)
        self.label_titel.setTextFormat(QtCore.Qt.RichText)
        self.label_titel.setWordWrap(False)
        self.label_titel.setObjectName("label_titel")
        self.verticalLayout_6.addWidget(self.label_titel)
        self.label_casus_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_casus_1.setTextFormat(QtCore.Qt.RichText)
        self.label_casus_1.setWordWrap(True)
        self.label_casus_1.setObjectName("label_casus_1")
        self.verticalLayout_6.addWidget(self.label_casus_1)
        self.label_casus_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_casus_2.setText("")
        self.label_casus_2.setTextFormat(QtCore.Qt.RichText)
        self.label_casus_2.setWordWrap(True)
        self.label_casus_2.setObjectName("label_casus_2")
        self.verticalLayout_6.addWidget(self.label_casus_2)
        self.label_casus_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_casus_3.setText("")
        self.label_casus_3.setTextFormat(QtCore.Qt.RichText)
        self.label_casus_3.setWordWrap(True)
        self.label_casus_3.setObjectName("label_casus_3")
        self.verticalLayout_6.addWidget(self.label_casus_3)
        self.label_casus_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_casus_4.setText("")
        self.label_casus_4.setTextFormat(QtCore.Qt.RichText)
        self.label_casus_4.setWordWrap(True)
        self.label_casus_4.setObjectName("label_casus_4")
        self.verticalLayout_6.addWidget(self.label_casus_4)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.radioButton_a = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_a.sizePolicy().hasHeightForWidth())
        self.radioButton_a.setSizePolicy(sizePolicy)
        self.radioButton_a.setText("")
        self.radioButton_a.setObjectName("radioButton_a")
        self.verticalLayout_17.addWidget(self.radioButton_a)
        self.radioButton_b = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_b.sizePolicy().hasHeightForWidth())
        self.radioButton_b.setSizePolicy(sizePolicy)
        self.radioButton_b.setText("")
        self.radioButton_b.setObjectName("radioButton_b")
        self.verticalLayout_17.addWidget(self.radioButton_b)
        self.radioButton_c = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_c.sizePolicy().hasHeightForWidth())
        self.radioButton_c.setSizePolicy(sizePolicy)
        self.radioButton_c.setText("")
        self.radioButton_c.setObjectName("radioButton_c")
        self.verticalLayout_17.addWidget(self.radioButton_c)
        self.radioButton_d = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_d.sizePolicy().hasHeightForWidth())
        self.radioButton_d.setSizePolicy(sizePolicy)
        self.radioButton_d.setText("")
        self.radioButton_d.setObjectName("radioButton_d")
        self.verticalLayout_17.addWidget(self.radioButton_d)
        self.horizontalLayout.addLayout(self.verticalLayout_17)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_a = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_a.sizePolicy().hasHeightForWidth())
        self.label_a.setSizePolicy(sizePolicy)
        self.label_a.setTextFormat(QtCore.Qt.RichText)
        self.label_a.setWordWrap(True)
        self.label_a.setObjectName("label_a")
        self.verticalLayout_22.addWidget(self.label_a)
        self.label_b = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_b.sizePolicy().hasHeightForWidth())
        self.label_b.setSizePolicy(sizePolicy)
        self.label_b.setTextFormat(QtCore.Qt.RichText)
        self.label_b.setWordWrap(True)
        self.label_b.setObjectName("label_b")
        self.verticalLayout_22.addWidget(self.label_b)
        self.label_c = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_c.sizePolicy().hasHeightForWidth())
        self.label_c.setSizePolicy(sizePolicy)
        self.label_c.setTextFormat(QtCore.Qt.RichText)
        self.label_c.setWordWrap(True)
        self.label_c.setObjectName("label_c")
        self.verticalLayout_22.addWidget(self.label_c)
        self.label_d = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_d.sizePolicy().hasHeightForWidth())
        self.label_d.setSizePolicy(sizePolicy)
        self.label_d.setTextFormat(QtCore.Qt.RichText)
        self.label_d.setWordWrap(True)
        self.label_d.setObjectName("label_d")
        self.verticalLayout_22.addWidget(self.label_d)
        self.horizontalLayout.addLayout(self.verticalLayout_22)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 18))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titel.setText(_translate("MainWindow", "Voorbeeld casus: Meneer Piet"))
        self.label_casus_1.setText(_translate("MainWindow", "Meneer Piet (47) heeft last van buikpijn in het rechtsboven kwadrant, misselijkheid en toename van pijn na het eten."))
        self.label_2.setText(_translate("MainWindow", "Hoe zou je Piet diagnosticeren?"))
        self.label_a.setText(_translate("MainWindow", "A. Galstenen"))
        self.label_b.setText(_translate("MainWindow", "B. Galstenen"))
        self.label_c.setText(_translate("MainWindow", "C. Galstenen"))
        self.label_d.setText(_translate("MainWindow", "D. Galstenen"))
        self.label_4.setText(_translate("MainWindow", "\"Waarschijnlijk is het C, Maag Ulcer.\""))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))

